### ISSUE TITLE
FYI: Block implicitly retains 'self'

### ISSUE THREAD

**Issue by andrewstephenson-v1** [JonasGessner/JGActionSheet#7]
Hi,

I'm using the very latest version.

There are 22 instances of the above warning, XCode is suggesting insert "self->"

**Comment by JonasGessner** [comment]
Strange. What version of Xcode? Also can you show me a screenshot f the warnings & the lines?

**Comment by andrewstephenson-v1** [comment]
Using Xcode 6.1

I have 'Implicit retain of 'self' within blocks' warning set to Yes.

.m lines:
606, 607, 850, 860, 863, 864, 868, 869, 873, 887, 889, 891-4, 986-7, 989, 993-5

![screen shot 2014-11-22 at 09 53 32](https://cloud.githubusercontent.com/assets/338667/5153729/955dce7c-722d-11e4-9434-900f4e1cf5d6.png)

**Comment by JonasGessner** [comment]
I've looked at this now, if `self` is referenced by blocks like UIView animation blocks or GCD blocks then it isn't a problem. Unless a retain cycle is created (for example if `self` references the block strongly, and the block references `self` you end up with a retain cycle) but UIView animation blocks and GCD blocks are not referenced by `self`/JGActionSheet therefore this isn't a problem and the warnings are just a bit silly. Actually, it might be better to reference self strongly in such blocks. It makes sure that as long as the block is not freed, `self` will also not be released, so that the block can properly finish what it should do, without ending up with a nil reference to `self` (`weakSelf` in that case).
